name: Divar Job Alert

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  test-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          RESPONSE=$(curl -sS -X POST \
            "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="110744941" \
            --data-urlencode text="✅ اتصال GitHub به ربات تلگرام برقرار شد.")

          echo "$RESPONSE"
