name: Divar Job Alert

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  test-divar:
    runs-on: ubuntu-latest

    steps:
      - name: Test Divar API
        run: |
          python - <<'PY'
          import requests

          url = "https://api.divar.ir/v8/postlist/w/search"

          payload = {
              "city_ids": ["1"],
              "search_data": {
                  "form_data": {
                      "data": {}
                  }
              },
              "pagination_data": {
                  "@type": "type.googleapis.com/post_list.PaginationData",
                  "page": 1
              }
          }

          headers = {
              "User-Agent": "Mozilla/5.0",
              "Content-Type": "application/json",
              "Origin": "https://divar.ir",
              "Referer": "https://divar.ir/"
          }

          r = requests.post(
              url,
              json=payload,
              headers=headers,
              timeout=30
          )

          print("STATUS:", r.status_code)
          print(r.text[:5000])
          PY
